return {
	Names = {
		TOOLBAR = "prefab",
		TOGGLE_BUTTON_TITLE = "Toggle",
		TOGGLE_BUTTON_TOOLTIP = "Toggles all of the prefabs between parts and real models",
	},

	Images = {
		TOOGLE_BUTTON_ICON = "rbxassetid://413367266",
	},

	Settings = {
		SHIFT_DOWN_FROM_PLACEHOLDER = "SHIFT_DOWN_FROM_PLACEHOLDER",
		MAKE_PRIMARY_PART_INVISIBLE = "MAKE_PRIMARY_PART_INVISIBLE",
		PREFAB_TAG_PATTERN = "PREFAB_TAG_PATTERN",
		PREFAB_VISIBILITY_OBJECT_VALUE_NAME = "PREFAB_VISIBILITY_OBJECT_VALUE_NAME",
	},
}